index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

messagerie:
    path:     /message{sujet_id}
    defaults: { _controller: AppBundle:Default:addmessage }
    requirements:
        _method: POST
        id: \d+

topic_new:
    path:     /nouveau_sujet
    defaults: { _controller: AppBundle:Default:createTopic }

topic_list:
    path:     /sujets
    defaults: { _controller: AppBundle:Default:list }

topic_show:
    path:     /sujets/{id}
    defaults: { _controller: AppBundle:Default:show }
