index:
    path:     /
    defaults: { _controller: AppBundle:Default:index}

messagerie:
    path:     /message
    defaults: { _controller: AppBundle:Default:addmessage}

show:
    path:     /conversation
    defaults: { _controller: AppBundle:Default:show}
    


